### ISSUE TITLE
Interaction Features

### ISSUE THREAD

**Issue by Delawen** [Delawen/codeCombat-LeafletOpenLayers#3]
PARA EL MAPA
PARA LAS CAPAS

**Comment by moiarcsan** [comment]
Para el mapa eventos tales como: doble clic zoom, clic en el mapa, menú contextual ...
Para las capas eventos tales como: clic, mouseover, menú contextual ...

Yo pondría un ejemplo con el mapa, como el que aparece en la documentación de Leaflet
http://leafletjs.com/examples/choropleth.html
