### ISSUE TITLE
Visual Features

### ISSUE THREAD

**Issue by Delawen** [Delawen/codeCombat-LeafletOpenLayers#4]
MOVIMIENTO DEL MAPA
MOVIMIENTO DE MARCAS

**Comment by moiarcsan** [comment]
Yo esta sección creo que revisándola bien con la documentación de Leaflet creo que no tiene sentido. Porque al principio le dí una separación a Interaction Feature, a la funcionalidad que interactua con las capas y con el mapa. Pero en verdad Visual Features lo pensé como la posibilidad de interactuar con marcas mediante los movimientos de las mismas, pero creo que se puede incluir directamente en la sección de Interacción ya que ahí se engloba a ambas.

¿Qué te parece si eliminamos esta sección?¿Pondrías alguna otra sección más?

**Comment by Delawen** [comment]
Yo de hecho creo que para 20 minutos de presentación vamos sobrados. Y si falta, mencionamos OL3.
