### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by Delawen** [Delawen/codeCombat-LeafletOpenLayers#6]
EN ORDENADOR
EN MÓVIL Y TABLET

**Comment by Delawen** [comment]
OpenLayers:

Escritorio:
- IE6+
- Firefox
- Google Chrome

Móvil:
¡¡Código específico para móvil que se carga automáticamente!!
- iOS 1+
- Android

**Comment by moiarcsan** [comment]
Leaflet

Escritorio:
- Chrome
- Firefox
- Safari 5+
- Opera 12+
- IE 7–11

Móvil:
- Navegador Safari de iOS 3–7+
- Navegador de Android 2.2+, 3.1+, 4+
- Chrome para Android 4+ y iOS
- Firefox para Android
- Otros navegadores WebKit (webOS, Blackberry 7+, etc.)
- IE10/11 para dispositivos con Win8
