### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by Delawen** [Delawen/codeCombat-LeafletOpenLayers#7]
Changing style

**Comment by Delawen** [comment]
OpenLayers:
- Cambiar estilo de features vectoriales: fácil
- Cambiar estilo general del mapa (CSS, iconos): difícil

**Comment by moiarcsan** [comment]
Leaflet:
- Popups y controles con CSS3 puro para un fácil cambio de estilo
- Marcas basadas en Imágenes y HTML
- Una interfaz simple para implementar capas personalizadas
- Lo mismo para personalizar los controles del mapa
- Proyecciones del mapa personalizadas (con EPSG:4326, EPSG:3857 y EPSG:3395 fuera del encuadre)
- Facilidades POO para extender clases existentes
