### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by Delawen** [Delawen/codeCombat-LeafletOpenLayers#8]
Easiness to develop

**Comment by Delawen** [comment]
OpenLayers:

En OpenLayers no existen los plugins como tal, se pueden desarrollar nuevos controles y tipos de capas.

``` javascript
var control = new OpenLayers.Control();
OpenLayers.Util.extend(control, {
    draw: function () {
        // this Handler.Box will intercept the shift-mousedown
        // before Control.MouseDefault gets to see it
        this.box = new OpenLayers.Handler.Box( control,
            {"done": this.notice},
            {keyMask: OpenLayers.Handler.MOD_SHIFT});
        this.box.activate();
    },

    notice: function (bounds) {
        OpenLayers.Console.userError(bounds);
    }
});
map.addControl(control);
```

**Comment by moiarcsan** [comment]
En Leaflet existe una página dentro de la documentación dedicada a los plugins [1] que se pueden incluir para obtener funcionalidad extra. La modularidad de Leaflet a través de sus plugins es una de sus ventajas, ya que el core de la aplicación es ligero, ya que muchas de las funcionalidades están desarrolladas en plugins, por lo que puedes usar la funcionalidad que necesites sin necesidad de tener todas en el código principal.

La forma de usarlo es cargar en nuestro código el plugin que necesitemos y usarlo directamente. Por ejemplo incluímos el código del plugin Leaflet Control Geocoder [2] y lo usamos:

Cargamos CSS y Javascript:

``` html
<link rel="stylesheet" href="../Control.Geocoder.css" />
<script src="Control.Geocoder.js"></script>
```

Add the control to a map instance:

``` javascript
var map = L.map('map').setView([0, 0], 2);
L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);
L.Control.geocoder().addTo(map);
```

[1] http://leafletjs.com/plugins.html
[2] https://github.com/perliedman/leaflet-control-geocoder
